force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/IsCorrect__c.field-meta.xml
<CustomField>
    <fullName>IsCorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCorrect?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question_Progress__c/Question_Progress__c.object-meta.xml
<CustomObject>
    <label>Question Progress</label>
    <nameField>
        <displayFormat>QP-{0000}</displayFormat>
        <label>Question Progress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions Progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Progress__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Questions Progress</relationshipLabel>
    <relationshipName>Questions_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Progress__c/fields/Unit_Progress__c.field-meta.xml
<CustomField>
    <fullName>Unit_Progress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Progress</label>
    <referenceTo>Unit_Progress__c</referenceTo>
    <relationshipLabel>Questions Progress</relationshipLabel>
    <relationshipName>Questions_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/Unit_Progress__c.object-meta.xml
<CustomObject>
    <label>Unit Progress</label>
    <nameField>
        <displayFormat>UP-{0000}</displayFormat>
        <label>Unit Progress Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Progress__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <label>Counter</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Units_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/updateStatusHelper.cls
public with sharing class updateStatusHelper{
    public static void updateUserUnitProg ( List<Unit_Progress__c> triggerNew) {
      
        Set<Id> unitIds = new Set<Id>();
        for(Unit_Progress__c unit: triggerNew){
            if(unit.Status__c == 'Answered'){
                unitIds.add(unit.Id);
            }
        }
        if(unitIds.size() != 0){

            List<Unit_Progress__c> unitProgressQuery = [SELECT Id, Name, Status__c, Counter__c, Points__c, User__c, (SELECT Id, Option__c, Option__r.IsCorrect__c FROM Questions_Progress__r) FROM Unit_Progress__c WHERE Id IN :unitIds];
            
            
            //Este set ↓ va a contener los User Ids obtenidos en la lista unitProgressQuery[linea 12], que estan vinculados con los Units_Progress__c. Estos Ids sirven para asegurarnos de que en usersFromUnitProgress[linea 22] llegen los mismos usuarios que recibimos como relacion(User__c) en unitProgressQuery[linea 12]
            Set<Id> userSet = new Set<Id>();
            
            for(Unit_Progress__c uProgress: unitProgressQuery){
                userSet.add(uProgress.User__c);
                System.debug(uProgress.Points__c);
            }
            
            //Necesitamos esta lista para poder setear los Points__c de User ↓
            List<User> usersFromUnitProgress = [SELECT Points__c, (SELECT Id FROM Units_Progress__r) FROM USER WHERE Id IN: userSet];
            System.debug(usersFromUnitProgress);
            //Este mapa ↓ vincula los mismos Ids de Unit_Progress__c que nos llegan en unitProgressQuery[linea 12], y que tambien pedimos en usersFromUnitProgress[linea 22], con los Users correctos(para poder hacer los loops[linea 27 y 28] y que correspondan). Esto va a servir para que cuando estemos haciendo loops[linea 34 y 35] sobre los registros que pedimos en unitProgressQuery[linea 12](Unit_Progress__c y Question_Progress__c) tambien podamos setear los Points__c de los Users correspondientes).
            Map<Id, Integer> userIndexByUnitProgress = new Map<Id, Integer>();
            for(User user: usersFromUnitProgress){
                for(Unit_Progress__c unitPro: user.Units_Progress__r){
                 System.debug(unitPro.Id);
                 System.debug(usersFromUnitProgress[usersFromUnitProgress.indexOf(user)].Points__c);
                    userIndexByUnitProgress.put(unitPro.Id, usersFromUnitProgress.indexOf(user));
                }
            }

            
            //COMENTARIO 09/10 mientras recorro las respuestas de las preguntas sumo en un contador las que fueron respodidas correctamente. Si la cantidad de respuesta respondidas correctamente iguala a la cantidad de preguntas seteo el unitProgress.Status__c en 'success'
            if(unitProgressQuery.size() != 0 ){
                for(Unit_Progress__c unitProgress : unitProgressQuery){
                    if(unitProgress.Counter__c == null){
                        unitProgress.Counter__c = 1;
                    }
                    Integer questionsAnsweredCorrectly = 0;
                    for(Question_Progress__c question : unitProgress.Questions_Progress__r) {
                        if(question.Option__r.IsCorrect__c){
                            questionsAnsweredCorrectly++;
                        }
                    }
                    if(questionsAnsweredCorrectly == unitProgress.Questions_Progress__r.size()){
                        unitProgress.Status__c = 'Success';
                        if(userIndexByUnitProgress.containsKey(unitProgress.Id)){
                            System.debug(unitProgress.Points__c + 'ACA');
                            usersFromUnitProgress[userIndexByUnitProgress.get(unitProgress.Id)].Points__c += unitProgress.Points__c;
                        }
                    }else if(unitProgress.Counter__c == 1){
                        unitProgress.Counter__c += 1; 
                        unitProgress.Status__c = 'Fail';
                        unitProgress.Points__c = unitProgress.Points__c/2;
                    }else if(unitProgress.Counter__c == 2){
                        unitProgress.Counter__c += 1; 
                        unitProgress.Status__c = 'Fail';
                        unitProgress.Points__c = unitProgress.Points__c/2;
                    }else if(unitProgress.Counter__c >= 3){
                        unitProgress.Counter__c += 1; 
                        unitProgress.Status__c = 'Fail';
                    }
                }
            }
            update unitProgressQuery;
             update usersFromUnitProgress;
        }
    }
}                  